config/routes.rb
Rails.application.routes.draw do
  root 'departments#index'

  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, except: [:index, :new, :create]

  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end

  def create 
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update 
    if @department.update(department_params)
      redirect_to departments_path
    else
      render :edit
    end
  end 

  def destroy 
    @department.destroy
    redirect_to departments_path
  end
end

private
    def set_department
      @department = Department.find(params[:id])
    end
  
    def department_params
      params.require(:department).permit(:name)
    end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, except: [:index, :new, :create]

  def index
    @items = @department.items
  end

  def show
  end

  def new
    @item = @department.items.new
    render partial: "form"
  end

  def create
    @item = @department.items.new(item_params)
    if @item.save
      redirect_to department_items_path
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to department_items_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to department_items_path
  end

  private
    def set_department
      @department = Department.find(params[:department_id])
    end

    def set_item
      @item = Item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? "Change Department" : "Which Department Would You Like To Enter?" %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Department Name" %>
  <%= f.submit %>
<% end %>

app/views/departments/index.html.erb
<h1>Click a Department To View Content</h1>

<%= link_to "Go to a new Department", new_department_path %>

<ul>
  <% @departments.each do |s| %>
    <li><%= link_to s.name, department_path(s) %></li>
  <% end %>
</ul>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to "View Items", department_items_path(@department) %>
<br />
<%= link_to "Change an Item", edit_department_path(@department) %>
<br />
<%= link_to "Remove an Item", department_path(@department), method: :delete %>
<br />
<br />
<br />
<p> --> <button><%= link_to "View Departments", departments_path %></button> <-- </p>

app/views/items/_form.html.erb
<h1><%= @item.id ? "Change Item" : "What Item Would You Like?" %></h1>

<hr /> 

<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true, placeholder: "Item" %>

  <br />

  <%= f.label :price %>
  <%= f.text_field :price, required: true, placeholder: "PRICE" %>

<br />

<%= f.submit %>

<% end %>

app/views/items/index.html.erb
<h1>Select and Item to View Details</h1>

<hr />

<%= link_to "Retrieve an Item", new_department_item_path(@department) %>

<ul>
  <% @items.each do |t| %>
    
    <li><%= link_to t.name, department_item_path(@department, t) %></li>

  <% end %>
</ul>

app/views/items/show.html.erb
<h1> <%= @department.name %> - <%= @item.name %> </h1>

<br />

<h3> <%= @item.price %> </h3>

<br />

<%= link_to 'Change Item', edit_department_item_path(@department, @item) %>

<br />

<%= link_to 'Remove an Item', department_item_path(@department), method: :delete %>

<br />

<%= link_to 'Back to Viewing Items', department_items_path(@department) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>